version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0.25
    ports:
      - "4000:3306"
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .dbdata:/var/lib/mysql