# Generated by Django 3.2.7 on 2022-03-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(db_column='profile_image', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
