# Generated by Django 4.0.3 on 2022-03-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
