# Generated by Django 4.0.3 on 2022-03-31 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_post_profileimage_post_username_post_writetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writeTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 10, 16, 22, 957670, tzinfo=utc)),
        ),
    ]
