# Generated by Django 4.0.3 on 2022-04-04 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_alter_post_writetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writeTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 13, 32, 6, 182509)),
        ),
    ]
