# Generated by Django 4.0.3 on 2022-04-04 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_alter_post_writetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writeTime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='글 작성 시간'),
        ),
    ]
